import fsp from "node:fs/promises";
import { addComponent, createResolver, defineNuxtModule } from "nuxt/kit";
import { parseAndRender, type JsParserOptions } from "@ox-content/napi";

type RenderedContent = {
  resolvedPath: string;
  content: string;
};

type MarkdownContent = {
  locale: string;
  relativePath: string;
  content: string;
};

const markdownOptions = {
  autolinks: true,
  gfm: true,
  strikethrough: true,
  tables: true,
  taskLists: true,
} satisfies JsParserOptions;

export default defineNuxtModule({
  meta: {
    name: "ox-content-prerender-module",
    configKey: "oxContentPrerender",
  },

  setup(_options, nuxt) {
    const resolver = createResolver(import.meta.url);
    const markdownContentRootDir = resolver.resolve("../i18n/");
    const componentsDir = resolver.resolve("../app/components/_i18n");

    nuxt.options.watch.push(markdownContentRootDir);

    setupNitroInitHook();
    setupBuilderWatchHook();

    function setupNitroInitHook() {
      nuxt.hook("nitro:init", async () => {
        await fsp.rm(componentsDir, { recursive: true, force: true }); // clear
        const rendered = await renderAll();
        await Promise.all(rendered.map((renderedContent) => write(renderedContent, true)));
      });
    }

    function setupBuilderWatchHook() {
      nuxt.hook("builder:watch", async (events, path) => {
        if (!path.startsWith(markdownContentRootDir) || !path.endsWith(".md")) return;

        const absolutePath = resolver.resolve(markdownContentRootDir, path);
        const relativePath = absolutePath.replace(markdownContentRootDir, "");
        const locale = relativePath.split("/")[relativePath.startsWith("/") ? 1 : 0]!;

        if (["add", "change"].includes(events)) {
          const markdownContent = await parseMarkdownFile(path);
          const renderedContent = await render(markdownContent);
          await write(renderedContent, events === "add");
        } else if (events === "unlink") {
          const outputFile = getOutputPath({ locale, relativePath, content: "" });
          await fsp.unlink(outputFile).catch();
        }
      });
    }

    async function renderAll() {
      const files = await fsp.readdir(markdownContentRootDir, { recursive: true });
      const markdownFiles = files.filter((file) => file.endsWith(".md"));
      const contents = await Promise.all(
        markdownFiles.map(async (file) => parseMarkdownFile(file)),
      );
      return await Promise.all(contents.map((markdownContent) => render(markdownContent)));
    }

    async function render(markdownContent: MarkdownContent): Promise<RenderedContent> {
      const isFaq = markdownContent.relativePath.endsWith("faq.md");
      const resolvedPath = getOutputPath(markdownContent);
      const content = await generateComponentContent(markdownContent, isFaq);
      return { resolvedPath, content };
    }

    async function generateComponentContent(
      markdownContent: MarkdownContent,
      isFaq: boolean,
    ): Promise<string> {
      const PROLOGUE = `<!-- This file is auto-generated by ox-content-prerender-module. Do not edit it manually. -->\n\n<template>\n<div data-vf-mdc>\n`;
      const EPILOGUE = `
  </div>
</template>
${isFaq ? generateFaqStyles() : ""}`;

      const renderedContent = renderComponentInnerContent(markdownContent, isFaq);

      return `${PROLOGUE}${renderedContent}${EPILOGUE}`;
    }

    function renderComponentInnerContent(markdownContent: MarkdownContent, isFaq: boolean): string {
      try {
        const rendered = renderMarkdown(markdownContent.content);
        return isFaq ? renderFAQ(rendered) : rendered;
      } catch (error) {
        console.warn(
          `Failed to render markdown with ox-content: ${markdownContent.relativePath}`,
          error,
        );
        return markdownContent.content;
      }
    }

    function renderMarkdown(content: string): string {
      const rendered = parseAndRender(content, markdownOptions);
      if (rendered.errors.length > 0) {
        throw new Error(rendered.errors.join("\n"));
      }
      return rendered.html;
    }

    function generateFaqStyles(): string {
      return `
<style scoped>
@import "~/assets/styles/custom-media-query.css";

h3.faq-q-wrapper {
  display: flex;
  margin-top: 40px;
  @media (--mobile-small) {
    margin-top: 32px;
  }
}

.faq-q,
.faq-a {
  border-radius: 50%;
  width: 28px;
  height: 28px;
  line-height: 28px;
  text-align: center;
  display: inline-block;
  margin-right: 8px;
  margin-top: -4px;
  font-weight: 700;

  @media (--mobile) {
    margin-top: -6px;
  }
}

.faq-q {
  color: var(--color-base);
  border: 1px solid var(--color-base);
}

.faq-a {
  color: var(--color-text-default);
  border: 1px solid var(--color-text-default);
}

.faq-a-content-wrapper {
  margin-top: 14px;
  display: flex;

  @media (--mobile-small) {
    margin-top: 12px;
  }
}

.faq-q-content,
.faq-a-content {
  flex: 1;
}
</style>`;
    }

    function renderFAQ(markdownHtml: string): string {
      const sections = markdownHtml.split(/(?=<h3(?:\s|>))/);

      return sections
        .map((section) => {
          if (!section.trim()) return "";

          const matches = section.match(/^<h3([^>]*)>(.*?)<\/h3>([\s\S]*)/);
          if (!matches) {
            return section;
          }

          const [, attributes, headingContent, answerContent] = matches;
          const headingAttributes = addClassAttribute(attributes!, "faq-q-wrapper");
          const processedHeader = `<h3${headingAttributes}><div class="faq-q">Q</div><div class="faq-q-content">${headingContent}</div></h3>`;

          if (!answerContent) {
            return processedHeader;
          }

          return `${processedHeader}<div class="faq-a-content-wrapper"><span class="faq-a">A</span><div class="faq-a-content">${answerContent}</div></div>`;
        })
        .join("");
    }

    function addClassAttribute(attributes: string, className: string): string {
      if (!attributes.trim()) {
        return ` class="${className}"`;
      }

      if (!/\sclass=/.test(attributes)) {
        return `${attributes} class="${className}"`;
      }

      return attributes.replace(/(\sclass=(["']))([^"']*)(\2)/, `$1${className} $3$4`);
    }

    async function parseMarkdownFile(path: string): Promise<MarkdownContent> {
      const absolutePath = resolver.resolve(markdownContentRootDir, path);
      const relativePath = absolutePath.replace(markdownContentRootDir, "");
      const locale = relativePath.split("/")[relativePath.startsWith("/") ? 1 : 0]!;
      const content = await fsp.readFile(absolutePath, "utf-8");
      return { locale, relativePath, content };
    }

    async function write(prc: RenderedContent, isNew = false): Promise<void> {
      const { resolvedPath, content } = prc;
      const dir = resolver.resolve(resolvedPath, "..");
      await fsp.mkdir(dir, { recursive: true });
      await fsp.writeFile(resolvedPath, content).catch();

      if (isNew) {
        registerComponent(resolvedPath);
      }
    }

    function registerComponent(resolvedPath: string) {
      addComponent({
        name: resolvedPath
          .replace(/\.vue$/, "")
          .split("/")
          .slice(-1)[0]!,
        filePath: resolvedPath,
        export: "default",
        global: true,
      });
    }

    function getOutputPath(markdownContent: MarkdownContent): string {
      // Add locale as prefix
      const componentName =
        markdownContent.locale.charAt(0).toUpperCase() +
        markdownContent.locale.slice(1) +
        markdownContent.relativePath
          .replace(/\.md$/, "")
          .split("/")
          // Remove locale name part
          .slice(2)
          // Remove "-"
          .flatMap((part) => part.split("-"))
          // To pascal case
          .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
          .join("");

      return resolver.resolve(componentsDir, markdownContent.locale, `${componentName}.vue`);
    }
  },
});
