$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - abramov
  - acconect
  - agentic
  - Ainoya
  - akinori
  - Akryum
  - alistaiir
  - allscale
  - allspeed
  - Alvarosabu
  - andpad
  - Aose
  - aoshi
  - arisa
  - arounds
  - astrotyotogood
  - astuki
  - atsuki
  - authjs
  - autodocs
  - autolinks
  - autospace
  - Backes
  - barai
  - bengo
  - bookfan
  - bsky
  - Bucky
  - bunx
  - burio
  - Catmull
  - ceroan
  - chau
  - chibivue
  - chiyoda
  - choco
  - chooseicon
  - Classmethod
  - cloudflarestorage
  - cloudsign
  - coderabbit
  - codmon
  - Colada
  - commandfor
  - Computeds
  - corons
  - cosme
  - cosmonic
  - crayfisher
  - Creatorsgarten
  - crowdsourcing
  - crowlKats
  - cyberagent
  - daaay
  - dagashi
  - Daisuke
  - danielroe
  - databank
  - dateness
  - dbaeumer
  - dearu
  - Delton
  - Denoland
  - dero
  - desumasu
  - dominikg
  - drumath
  - ebookjapan
  - Eluwing
  - Elysia
  - embla
  - emscripten
  - esbenp
  - escentier
  - evenodd
  - ffef
  - finatext
  - finetext
  - fract
  - frontends
  - ftechno
  - fujimmm
  - Fujimoto
  - Fujishiro
  - FUJITA
  - Fukuda
  - Furukawa
  - gaearon
  - genj
  - GLSL
  - Golar
  - gruntfuggly
  - guillaume
  - Gura
  - Haba
  - hackz
  - hacomono
  - hakshu
  - Hanabusa
  - Hanako
  - hannoeru
  - hanzomon
  - Haoqun
  - happylifetaka
  - Haruki
  - hashimoto
  - Hasuto
  - healthtech
  - hecateball
  - HENKA
  - hennge
  - HENNKA
  - hikkobay
  - hinomaru
  - Hiranuma
  - hiro
  - Hiroki
  - hiroko
  - hiroshi
  - Holo
  - icubedsystems
  - Ikeda
  - ikkyu
  - Ikuta
  - ikyu
  - Ilya
  - inputtext
  - intlify
  - ishii
  - istyle
  - Jabelic
  - Jiang
  - Jiro
  - jiyuujin
  - johnsoncodehk
  - JUCE
  - Junpei
  - Kaede
  - Kaigi
  - KALUPASU
  - Kambe
  - karacoro
  - karan
  - karancoro
  - karte
  - katanuki
  - Katashin
  - katayama
  - Kato
  - katsuhiro
  - kawaguchi
  - kazu
  - kazupon
  - kazuya
  - keigo
  - keihin
  - Keisuke
  - Kettmeir
  - keystyle
  - kgierke
  - Khunpanitchot
  - kiaking
  - kickflow
  - kinew
  - kinto
  - Kobari
  - kodomon
  - Kogure
  - koki
  - kokoe
  - Kongkeit
  - Kota
  - kotafujishiro
  - kouki
  - Koutaro
  - koya
  - koyasaeki
  - ktsn
  - ktym
  - kurawa
  - kzhrk
  - lacunarity
  - ldfcorp
  - leaysgur
  - lerp
  - lightningcss
  - lightshow
  - Livesense
  - livestreaming
  - LIXIL
  - lockfiles
  - Lokalise
  - lycorp
  - magcho
  - Markuplint
  - MagSafe
  - marunouchi
  - Masato
  - matcha
  - medpeer
  - metalness
  - mew-ton
  - minato
  - misaki
  - mita
  - miura
  - miyake
  - mizdra
  - mizukirimatsu
  - mnch
  - mnmxmx
  - moabear
  - mooncat
  - Moriguin
  - morishita
  - Morote
  - mozjpeg
  - Murata
  - NAGAI
  - naitokosuke
  - nakagam
  - nakagami
  - Nakahira
  - nakano
  - nakayama
  - nakayamaakinori
  - nami
  - Naoki
  - naokihaba
  - napi
  - naramochi
  - Natsuki
  - neginasu
  - Neko
  - Nijibox
  - Ninisan
  - Nishihara
  - nitropack
  - nixpkgs
  - Nobuaki
  - nofa
  - noindex
  - nokki
  - noopener
  - noreferrer
  - noriyuki
  - northprint
  - Nozomu
  - nozomuikuta
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - odan
  - ogawa
  - Okuyama
  - optim
  - Osame
  - otemachi
  - oxfmt
  - oxlint
  - palt
  - Parsa
  - pcnextbutton
  - pcprevbutton
  - peatix
  - pkgs
  - pontaxx
  - ponyoxa
  - Pooya
  - posva
  - posx
  - presigner
  - QUIC
  - Rahul
  - Rakuten
  - raycaster
  - rebranded
  - regle
  - reinit
  - Rinchoku
  - ritogk
  - RIZAP
  - RNBO
  - rolldown
  - rowspan
  - rstore
  - rymiyamoto
  - ryoaccount
  - ryuhei
  - Ryutaro
  - Saburo
  - saito
  - saltyaom
  - sano
  - sasagar
  - sasagawaki
  - Sasaki
  - Sato
  - Satouuuuuu
  - sayn
  - SCXML
  - senbei
  - Seyschab
  - Shigeyuki
  - shiminori
  - shimizu
  - Shingo
  - shinkansen
  - Shota
  - sidebase
  - sigrea
  - slidesinview
  - snufkin
  - softprops
  - Spidernight
  - ssssota
  - stockmark
  - studist
  - substep
  - substeps
  - sugiura
  - sumi
  - suminagashi
  - supporterz
  - takumi
  - tanaka
  - teachme
  - tebiki
  - techbowl
  - techworld
  - tenshoku
  - tenugui
  - terraformrc
  - Tetone
  - textareas
  - textlint
  - tfstate
  - tfvars
  - themarcba
  - themself
  - thiha
  - Thorsten
  - tiful
  - tigertrack
  - todde
  - toei
  - tohoku
  - tokaido
  - tokusho
  - Tomoda
  - totocalcio
  - toyo
  - tozai
  - tresjs
  - triaging
  - Tsai
  - tsgolint
  - Tsuchiya
  - Tsuji
  - tsukkee
  - tsuno
  - ubugeeei
  - uiuifree
  - unhead
  - uniquevision
  - unplugin
  - unrs
  - ushironoko
  - Verlet
  - vados
  - valibot
  - Vashishtha
  - vejhszh
  - Verter
  - visasq
  - Vite
  - Vize
  - vizejs
  - voidzero
  - vuefes
  - vuejs
  - Vuelidate
  - vuetify
  - vueuse
  - Wada
  - wattanx
  - webauthn
  - webgl
  - webshops
  - workerd
  - xlink
  - xmdx
  - XREAL
  - Yako
  - yamageji
  - yamanoku
  - yamanote
  - yappli
  - Yasunobu
  - ykoizumi
  - Yogo
  - yoshiya
  - Yosuke
  - Yuhei
  - Yuichi
  - yuichkun
  - yuji
  - Yuka
  - yuki
  - Yurika
  - Yusa
  - Yusuke
  - yusukebe
  - yuta
  - Yutaro
  - Yuto
  - zari
  - zauel
  - zauer
  - zeiri
  - Zeirishi
  - ZOZO
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
  - server/db/drizzle
  - CHANGELOG.md
