// Generated by @vizejs/nuxt.
import { readFileSync } from "node:fs";

type OxlintJsPlugin = string | { name?: string; specifier: string };

const generatedUrl = new URL("./.nuxt/oxlint.config.json", import.meta.url);
const config = JSON.parse(readFileSync(generatedUrl, "utf8"));
config.jsPlugins = config.jsPlugins.map((plugin: OxlintJsPlugin) =>
  typeof plugin === "string"
    ? new URL(plugin, generatedUrl).href
    : { ...plugin, specifier: new URL(plugin.specifier, generatedUrl).href },
);

export default config;
