/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/event/{eventId}/list_sales": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sales */
    get: operations["get_ListSalesGet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/event/{eventId}/list_sales/{salesId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sale */
    get: operations["get_SaleGet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_ListSalesGet: {
    parameters: {
      query?: {
        fresh?: string;
      };
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns a list of sales */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            sales: {
              salesId: string;
              eventId: string;
              ticketName: string;
            }[];
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
            message: string;
          };
        };
      };
    };
  };
  get_SaleGet: {
    parameters: {
      query?: {
        fresh?: string;
      };
      header?: never;
      path: {
        eventId: string;
        salesId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns a sale */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            salesId: string;
            eventId: string;
            ticketName: string;
          };
        };
      };
      /** @description Sale not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
            message: string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
            message: string;
          };
        };
      };
    };
  };
}
