import type { ProgramData } from "./types/program";

type ProgramDefinition<TId extends string> = ProgramData & { id: TId };

function definePrograms<const TId extends string>(
  programs: ProgramDefinition<TId>[],
): ProgramDefinition<TId>[] {
  return programs;
}

export const SESSION_PROGRAMS = definePrograms([
  {
    id: "opening",
    type: "session",
    speakerIds: [],
    start: "10:00",
    end: "10:10",
    tracks: ["track1", "track2"],
    ja: { title: "オープニング" },
    en: { title: "Opening" },
  },
  {
    id: "keynote",
    url: "",
    type: "session",
    speakerIds: ["yyx990803"],
    start: "10:10",
    end: "10:50",
    tracks: ["track1", "track2"],
    ja: { title: "キーノート", overview: "" },
    en: { title: "Keynote", overview: "" },
  },
  {
    id: "platinum-sponsor-session-1",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "10:55",
    end: "11:05",
    ja: { title: "" },
    en: { title: "" },
  },
  {
    id: "platinum-sponsor-session-2",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "10:55",
    end: "11:05",
    ja: { title: "" },
    en: { title: "" },
  },
  {
    id: "platinum-sponsor-session-3",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "11:05",
    end: "11:15",
    ja: { title: "" },
    en: { title: "" },
  },
  {
    id: "platinum-sponsor-session-4",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "11:05",
    end: "11:15",
    ja: { title: "" },
    en: { title: "" },
  },
  {
    id: "platinum-sponsor-session-5",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "11:15",
    end: "11:25",
    ja: { title: "" },
    en: { title: "" },
  },
  {
    id: "platinum-sponsor-session-6",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "11:15",
    end: "11:25",
    ja: { title: "" },
    en: { title: "" },
  },
  {
    id: "student-support-sponsor-session",
    type: "session",
    speakerIds: [],
    tracks: ["track4"],
    start: "11:30",
    end: "12:00",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-1",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "12:50",
    end: "13:20",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-2",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "12:50",
    end: "13:20",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-3",
    type: "session",
    speakerIds: [],
    tracks: ["track3"],
    start: "12:50",
    end: "13:20",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-4",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "13:35",
    end: "14:05",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-5",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "13:35",
    end: "14:05",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-6",
    type: "session",
    speakerIds: [],
    tracks: ["track3"],
    start: "13:35",
    end: "14:05",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-7",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "14:20",
    end: "14:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-8",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "14:20",
    end: "14:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-9",
    type: "session",
    speakerIds: [],
    tracks: ["track3"],
    start: "14:20",
    end: "14:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-10",
    type: "session",
    speakerIds: [],
    tracks: ["track1"],
    start: "15:05",
    end: "15:35",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-11",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "15:05",
    end: "15:35",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-12",
    type: "session",
    speakerIds: [],
    tracks: ["track3"],
    start: "15:05",
    end: "15:35",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-13",
    type: "session",
    speakerIds: [],
    tracks: ["track4"],
    start: "15:05",
    end: "15:35",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-14",
    type: "session",
    speakerIds: [],
    tracks: ["track3"],
    start: "15:50",
    end: "16:20",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-15",
    type: "session",
    speakerIds: [],
    tracks: ["track4"],
    start: "15:50",
    end: "16:20",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-16",
    type: "session",
    speakerIds: [],
    tracks: ["track4"],
    start: "16:35",
    end: "17:05",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-17",
    type: "session",
    speakerIds: [],
    tracks: ["track2"],
    start: "16:55",
    end: "17:25",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "session-18",
    type: "session",
    speakerIds: [],
    tracks: ["track4"],
    start: "17:20",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
]);

export const LIGHTNING_TALK_PROGRAMS = definePrograms([
  {
    id: "lunch-sponsor-lt-1",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "11:40",
    end: "11:45",
    ja: { title: "ランチスポンサーLT1" },
    en: { title: "Lunch Sponsor LT 1" },
  },
  {
    id: "lunch-sponsor-lt-2",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "11:50",
    end: "11:55",
    ja: { title: "ランチスポンサーLT2" },
    en: { title: "Lunch Sponsor LT 2" },
  },
  {
    id: "lunch-sponsor-lt-3",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "12:00",
    end: "12:05",
    ja: { title: "ランチスポンサーLT3" },
    en: { title: "Lunch Sponsor LT 3" },
  },
  {
    id: "lunch-sponsor-lt-4",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "12:10",
    end: "12:15",
    ja: { title: "ランチスポンサーLT4" },
    en: { title: "Lunch Sponsor LT 4" },
  },
  {
    id: "lightning-talk-1",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-2",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-3",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-4",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-5",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-6",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-7",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-8",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-9",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "lightning-talk-10",
    type: "lightningTalk",
    speakerIds: [],
    tracks: ["track3"],
    start: "16:35",
    end: "17:50",
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
]);

export const PANEL_DISCUSSION_PROGRAMS = definePrograms([
  {
    id: "panel-discussion-1",
    type: "panelDiscussion",
    speakerIds: [],
    start: "15:50",
    end: "16:50",
    tracks: ["track1"],
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
  {
    id: "panel-discussion-2",
    type: "panelDiscussion",
    speakerIds: [],
    start: "15:50",
    end: "16:50",
    tracks: ["track2"],
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
]);

export const EVENT_PROGRAMS = definePrograms([
  {
    id: "hands-on",
    type: "event",
    speakerIds: [],
    start: "12:50",
    end: "14:50",
    tracks: ["track4"],
    url: "/event?session=hands-on#hands-on",
    ja: { title: "ハンズオン" },
    en: { title: "Hands-on Workshop" },
  },
  {
    id: "student-support-contents",
    type: "event",
    speakerIds: [],
    start: "12:00",
    end: "12:30",
    tracks: ["track4"],
    ja: { title: "TBD" },
    en: { title: "TBD" },
  },
]);

export const PROGRAMS = [
  ...SESSION_PROGRAMS,
  ...LIGHTNING_TALK_PROGRAMS,
  ...PANEL_DISCUSSION_PROGRAMS,
  ...EVENT_PROGRAMS,
];

export type ProgramId = (typeof PROGRAMS)[number]["id"];
