import type { SpeakerData, StudentSupportSpeakerData } from "./types/speaker";

export const SESSION_SPEAKERS: SpeakerData[] = [
  {
    id: "yyx990803",
    avatarUrl: "/images/avatars/evan-you.jpeg",
    color: "default",
    attendedIndex: 1,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/youyuxi",
      bluesky: "https://bsky.app/profile/evan.me",
      github: "https://github.com/yyx990803",
      mastodon: "",
    },
    ja: {
      name: "Evan You",
      title: "CEO",
      affiliation: "VoidZero",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Evan You",
      title: "CEO",
      affiliation: "VoidZero",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "posva",
    avatarUrl: "/images/avatars/eduardo-san-martin-morote.png",
    color: "default",
    attendedIndex: 2,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/posva",
      bluesky: "https://bsky.app/profile/esm.dev",
      github: "https://github.com/posva",
      mastodon: "",
    },
    ja: {
      name: "Eduardo San Martin Morote (Posva)",
      title: "Vue.jsコアチーム",
      affiliation: "Vercel",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Eduardo San Martin Morote",
      title: "Vue.js Core Team",
      affiliation: "Vercel",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "pi0",
    avatarUrl: "/images/avatars/pooya-parsa.png",
    color: "default",
    attendedIndex: 3,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/_pi0_",
      bluesky: "https://bsky.app/profile/pi0.io",
      github: "https://github.com/pi0",
      mastodon: "",
    },
    ja: {
      name: "Pooya Parsa",
      title: "Nitro、UnJS、H3作者",
      affiliation: "Vercel",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Pooya Parsa",
      title: "Creator of Nitro, UnJS and H3",
      affiliation: "Vercel",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "ubugeeei",
    avatarUrl: "/images/avatars/ubugeeei.jpeg",
    color: "default",
    attendedIndex: 4,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/ubugeeei",
      bluesky: "",
      github: "https://github.com/ubugeeei",
      mastodon: "",
    },
    ja: {
      name: "ubugeeei",
      title: "Vize、chibivue作者",
      affiliation: "Vue.js、Vite+コアチーム",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "ubugeeei",
      title: "Creator of Vize and chibivue",
      affiliation: "Vue.js, Vite+ Core Team",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "mnmxmx",
    avatarUrl: "/images/avatars/misaki-nakano.png",
    color: "default",
    attendedIndex: 5,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/misaki_mofujp",
      bluesky: "",
      github: "https://github.com/mnmxmx",
      mastodon: "",
    },
    ja: {
      name: "中野 美咲",
      title: "WebGLデベロッパー",
      affiliation: "",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Misaki Nakano",
      title: "WebGL Developer",
      affiliation: "",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "crowlKats",
    avatarUrl: "/images/avatars/leo-kettmeir.jpeg",
    color: "default",
    attendedIndex: 6,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/crowlKats",
      bluesky: "",
      github: "https://github.com/crowlKats",
      mastodon: "",
    },
    ja: {
      name: "Leo Kettmeir",
      title: "",
      affiliation: "Denoland",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Leo Kettmeir",
      title: "",
      affiliation: "Denoland",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "alii",
    avatarUrl: "/images/avatars/alistair-smith.png",
    color: "default",
    attendedIndex: 7,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/alistaiir",
      bluesky: "",
      github: "https://github.com/alii",
      mastodon: "",
    },
    ja: {
      name: "Alistair Smith",
      title: "テクニカルスタッフ",
      affiliation: "Anthropic",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Alistair Smith",
      title: "Member of Technical Staff",
      affiliation: "Anthropic",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "SaltyAom",
    avatarUrl: "/images/avatars/kongkeit-khunpanitchot.jpeg",
    color: "default",
    attendedIndex: 8,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/saltyaom",
      bluesky: "",
      github: "https://github.com/SaltyAom",
      mastodon: "",
    },
    ja: {
      name: "Kongkeit Khunpanitchot (aka saltyaom)",
      title: "ソフトウェアエンジニア",
      affiliation: "Creatorsgarten",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Kongkeit Khunpanitchot (aka saltyaom)",
      title: "Software Engineer",
      affiliation: "Creatorsgarten",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "yusukebe",
    avatarUrl: "/images/avatars/yusuke-wada.jpeg",
    color: "default",
    attendedIndex: 9,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/yusukebe",
      bluesky: "https://bsky.app/profile/yusukebe",
      github: "https://github.com/yusukebe",
      mastodon: "",
    },
    ja: {
      name: "Yusuke Wada",
      title: "デベロッパーアドボケイト",
      affiliation: "Cloudflare, Inc.",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Yusuke Wada",
      title: "Developer Advocate",
      affiliation: "Cloudflare, Inc.",
      talkTitle: "",
      talkOverview: "",
    },
  },
  {
    id: "yosuke-furukawa",
    avatarUrl: "/images/avatars/yosuke-furukawa.jpeg",
    color: "default",
    attendedIndex: 10,
    sponsorId: undefined,
    slide: "",
    talkSchedule: "",
    talkTrack: undefined,
    socialUrls: {
      x: "https://x.com/yosuke_furukawa",
      bluesky: "https://bsky.app/profile/yosuke-furukawa.bsky.social",
      github: "https://github.com/yosuke-furukawa",
      mastodon: "",
    },
    ja: {
      name: "古川 陽介",
      title: "グループマネージャー / Japan Node.js Association代表理事",
      affiliation: "株式会社リクルート / 株式会社ニジボックス（デベロップメント室 室長）",
      talkTitle: "",
      talkOverview: "",
    },
    en: {
      name: "Yosuke Furukawa",
      title: "Group Manager / Representative Director, Japan Node.js Association",
      affiliation: "Recruit Co., Ltd. / Nijibox Co., Ltd. (Head of Development Office)",
      talkTitle: "",
      talkOverview: "",
    },
  },
];

// TODO: 2026 年度のスピーカー情報を追加する
export const LT_SPEAKERS: SpeakerData[] = [];

// TODO: 2026 年度のスピーカー情報を追加する
export const PANEL_DISCUSSION_SPEAKERS: SpeakerData[] = [];

// TODO: 2026 年度のスピーカー情報を追加する
export const STUDENT_SUPPORT_SPEAKERS: StudentSupportSpeakerData[] = [];
