name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check:
    name: Pre-merge Check and Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@49c3e4e92c52e7f8392712a9267bbe71c5ab30e5 # v1.19.0
        with:
          version: "0.1.11"
          node-version: "24.14.0"
          cache: true
          run-install: false

      - name: Install deps
        run: vp install --frozen-lockfile

      - name: Check changed files
        run: vp run --cache check:staged
        env:
          VP_STAGED_DIFF: ${{ github.event.pull_request.base.sha }}...HEAD

      - name: Typecheck
        run: vp run --cache typecheck

      - name: Build
        run: vp run --no-cache build
        env:
          APP_ENV: ci
          APP_ORIGIN: https://ci.example.com
          NODE_OPTIONS: "--max-old-space-size=4096"
          NUXT_BASE_PATH: /2026/
          NUXT_SITE_URL: https://ci.example.com/
          AUTH_SECRET: dummy
          CLOUDFLARE_API_TOKEN: dummy
          CLOUDFLARE_ACCOUNT_ID: dummy
          CLOUDFLARE_DATABASE_ID: dummy
          CLOUDFLARE_R2_ACCESS_KEY_ID: dummy
          CLOUDFLARE_R2_SECRET_ACCESS: dummy
          CLOUDFLARE_R2_BUCKET_NAME: dummy
          OAUTH_GITHUB_CLIENT_ID: dummy
          OAUTH_GITHUB_CLIENT_SECRET_ID: dummy
          OAUTH_GOOGLE_CLIENT_ID: dummy
          OAUTH_GOOGLE_CLIENT_SECRET: dummy
          PEATIX_API_ORIGIN: https://example.com
          PEATIX_API_SECRET: dummy
          PEATIX_EVENT_ID: dummy
