name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://vuefes.jp/2026/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          CONTEXT: production
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS }}
          OAUTH_GITHUB_CLIENT_SECRET_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET_ID }}
          OAUTH_GOOGLE_CLIENT_SECRET_ID: ${{ secrets.OAUTH_GOOGLE_CLIENT_SECRET_ID }}
          PEATIX_API_SECRET: ${{ secrets.PEATIX_API_SECRET }}
          AUTH_ORIGIN: ${{ vars.AUTH_ORIGIN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_DATABASE_ID: ${{ vars.CLOUDFLARE_DATABASE_ID }}
          CLOUDFLARE_R2_BUCKET_NAME: ${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}
          OAUTH_GITHUB_CLIENT_ID: ${{ vars.OAUTH_GITHUB_CLIENT_ID }}
          OAUTH_GOOGLE_CLIENT_ID: ${{ vars.OAUTH_GOOGLE_CLIENT_ID }}
          PEATIX_API_ORIGIN: ${{ vars.PEATIX_API_ORIGIN }}
          PEATIX_EVENT_ID: ${{ vars.PEATIX_EVENT_ID }}

      - name: Deploy to Netlify (Production)
        run: pnpm netlify deploy --no-build --prod --dir=.output/public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
